ALTER TABLE customer DROP CONSTRAINT fk, ADD CONSTRAINT fk FOREIGN KEY (c_nationkey) REFERENCES nation ON UPDATE CASCADE;
ALTER TABLE supplier DROP CONSTRAINT fk, ADD CONSTRAINT fk FOREIGN KEY (s_nationkey) REFERENCES nation ON UPDATE CASCADE;
